cities_in_israel_en_heb = {'Afula': 'עפולה', 'Arad': 'ערד', 'Ariel': 'אריאל', 'Ashdod': 'אשדוד', 'Ashkelon': 'אשקלון',
                           'Arraba': 'עראבה',
                           'Baqa-Jatt': "באקה-ג'ת", 'Bat Yam': 'בת ים', "Be'er Sheva": 'באר שבע',
                           "Beit She'an": 'בית שאן',
                           'Beit Shemesh': 'בית שמש', 'Baqa al-Gharbiyye': 'באקה אל-גרבייה',
                           'Beitar Illit': 'ביתר עילית', 'Bnei Brak': 'בני ברק',
                           'Dimona': 'דימונה', 'Eilat': 'אילת', "El'ad": 'אלעד', "Giv'atayim": 'גבעתיים',
                           "Giv'at Shmuel": 'גבעת שמואל',
                           'Hadera': 'חדרה', 'Haifa': 'חיפה', 'Herzliya': 'הרצליה', 'Hod Hasharon': 'הוד השרון',
                           'Holon': 'חולון',
                           'Jerusalem': 'ירושלים', 'Karmiel': 'כרמיאל', 'Kafr Qasim': 'כפר קאסם',
                           'Kefar Sava': 'כפר סבא',
                           'Kiryat Ata': 'קריית אתא', 'Kiryat Bialik': 'קריית ביאליק', 'Kiryat Gat': 'קריית גת',
                           'Kiryat Malakhi': 'קריית מלאכי',
                           'Kiryat Motzkin': 'קריית מוצקין', 'Kiryat Ono': 'קריית אונו', 'Kiryat Shmona': 'קריית שמונה',
                           'Kiryat Yam': 'קריית ים',
                           'Lod': 'לוד', "Ma'ale Adumim": 'מעלה אדומים', "Ma'alot-Tarshiha": 'מעלות תרשיחא',
                           'Migdal HaEmek': 'מגדל העמק',
                           "Modi'in Illit": 'מודיעין עילית', "Modi'in-Maccabim-Re'ut": 'מודיעין- מכבים- רעות',
                           'Maghar': "מע'אר",
                           'Nahariyya': 'נהריה', 'Nazareth': 'נצרת', 'Nazareth Illit': 'נצרת עלית', 'Nesher': 'נשר',
                           'Ness Ziona': 'נס ציונה',
                           'Netanya': 'נתניה', 'Netivot': 'נתיבות', 'Ofakim': 'אופקים', 'Or Akiva': 'אור עקיבא',
                           'Or Yehuda': 'אור יהודה',
                           'Nof HaGalil': 'נוף הגליל', 'Petah Tikva': 'פתח תקווה', 'Qalansawe': 'קלנסווה',
                           "Raanana": 'רעננה', 'Rahat': 'רהט',
                           'Ramat Gan': 'רמת גן', 'Ramat HaSharon': 'רמת השרון', 'Ramla': 'רמלה', 'Rehovot': 'רחובות',
                           'Rishon LeZion': 'ראשון לציון', 'Rosh HaAyin': 'ראש העין', 'Zefat': 'צפת',
                           'Sakhnin': 'סכנין', 'Sderot': 'שדרות',
                           "Shefa-Amr (Shfar'am)": 'שפרעם', 'Tamra': 'טמרה', 'Tayibe': 'טייבה',
                           'Tel-Aviv': 'תל אביב-יפו', 'Tiberias': 'טבריה',
                           'Tira': 'טירה', 'Tirat Carmel': 'טירת כרמל', 'Umm al-Fahm': 'אום אל-פחם', 'Yavne': 'יבנה',
                           'Yehud-Monosson': 'יהוד-מונסון', 'Pardesiya': 'פרדסיה', 'Yokneam': 'יקנעם עילית'}

cities_less_50_km_english = {'Afula': ['Nahariyya', 'Afula', 'Zefat', 'Haifa', 'Pardesiya'],
                             'Ariel': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                       'Bnei Brak',
                                       'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Ashdod': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Ashdod',
                                        'Bnei Brak',
                                        'Tel-Aviv', 'Hod Hasharon'], 'Ashkelon': ['Holon', 'Ashdod'],
                             'Arraba': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Baqa-Jatt': ['Kefar Sava', 'Petah Tikva', 'Raanana', 'Afula', 'Haifa', 'Ramat Gan',
                                           'Bnei Brak',
                                           'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Bat Yam': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Ashdod',
                                         'Bnei Brak',
                                         'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             "Be'er Sheva": ["Be'er Sheva"],
                             "Beit She'an": ['Afula'],
                             'Beit Shemesh': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Ramat Gan', 'Ashdod',
                                              'Bnei Brak', 'Tel-Aviv', 'Hod Hasharon'],
                             'Baqa al-Gharbiyye': ['Kefar Sava', 'Petah Tikva', 'Raanana', 'Afula', 'Haifa',
                                                   'Ramat Gan',
                                                   'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Beitar Illit': ['Jerusalem', 'Petah Tikva', 'Holon', 'Ramat Gan', 'Ashdod'],
                             'Bnei Brak': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                           'Ashdod',
                                           'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Dimona': ["Be'er Sheva"],
                             "El'ad": ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                       'Ashdod',
                                       'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             "Giv'atayim": ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                            'Ashdod',
                                            'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             "Giv'at Shmuel": ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana',
                                               'Ramat Gan',
                                               'Ashdod', 'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya',
                                               'Hod Hasharon'],
                             'Hadera': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Afula', 'Haifa', 'Ramat Gan',
                                        'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Haifa': ['Nahariyya', 'Afula', 'Haifa'],
                             'Herzliya': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Ashdod',
                                          'Bnei Brak',
                                          'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Hod HaSharon': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Ashdod',
                                              'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Holon': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                       'Ashdod',
                                       'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Jerusalem': ['Jerusalem', 'Petah Tikva', 'Holon', 'Ramat Gan', 'Bnei Brak'],
                             'Karmiel': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Kafr Qasim': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                            'Ashdod',
                                            'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Kfar Saba': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Ashdod',
                                           'Bnei Brak',
                                           'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Kiryat Ata': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Kiryat Bialik': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Kiryat Gat': ['Jerusalem', 'Holon', 'Ashdod', "Be'er Sheva"],
                             'Kiryat Malakhi': ['Jerusalem', 'Petah Tikva', 'Holon', 'Ramat Gan', 'Ashdod', 'Bnei Brak',
                                                'Tel-Aviv', 'Hod Hasharon'],
                             'Kiryat Motzkin': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Kiryat Ono': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                            'Ashdod',
                                            'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Kiryat Shmona': ['Zefat'], 'Kiryat Yam': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Lod': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                     'Ashdod',
                                     'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             "Ma'ale Adumim": ['Jerusalem'],
                             "Ma'alot-Tarshiha": ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Migdal HaEmek': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             "Modi'in Illit": ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana',
                                               'Ramat Gan',
                                               'Ashdod', 'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya',
                                               'Hod Hasharon'],
                             "Modi'in-Maccabim-Re'ut": ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana',
                                                        'Ramat Gan', 'Ashdod', 'Bnei Brak', 'Netanya', 'Tel-Aviv',
                                                        'Pardesiya',
                                                        'Hod Hasharon'],
                             'Maghar': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Nahariya': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Nazareth': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Nazareth Illit': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Nesher': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Ness Ziona': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                            'Ashdod',
                                            'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Netanya': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Bnei Brak',
                                         'Netanya',
                                         'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'], 'Netivot': ['Ashdod', "Be'er Sheva"],
                             'Ofakim': ["Be'er Sheva"],
                             'Or Akiva': ['Kefar Sava', 'Petah Tikva', 'Raanana', 'Afula', 'Haifa', 'Bnei Brak',
                                          'Netanya',
                                          'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Or Yehuda': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                           'Ashdod',
                                           'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Nof HaGalil': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Petah Tikva': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                             'Ashdod', 'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Qalansawe': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Afula', 'Ramat Gan',
                                           'Bnei Brak',
                                           'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             "Ra'anana": ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Ashdod',
                                          'Bnei Brak',
                                          'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Rahat': ['Ashdod', "Be'er Sheva"],
                             'Ramat Gan': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                           'Ashdod',
                                           'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Ramat HaSharon': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Ashdod',
                                                'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Ramla': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                       'Ashdod',
                                       'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Rehovot': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                         'Ashdod',
                                         'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Rishon LeZion': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana',
                                               'Ramat Gan',
                                               'Ashdod', 'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya',
                                               'Hod Hasharon'],
                             'Rosh HaAyin': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                             'Ashdod', 'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Safed': ['Nahariyya', 'Afula', 'Zefat'],
                             'Sakhnin': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Sderot': ['Ashdod', "Be'er Sheva"],
                             "Shefa-Amr (Shfar'am)": ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Tamra': ['Nahariyya', 'Afula', 'Zefat', 'Haifa'],
                             'Tayibe': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Afula', 'Ramat Gan',
                                        'Bnei Brak',
                                        'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Tel Aviv': ['Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan', 'Ashdod',
                                          'Bnei Brak',
                                          'Netanya', 'Tel-Aviv', 'Pardesiya', 'Hod Hasharon'],
                             'Tiberias': ['Nahariyya', 'Afula', 'Zefat'],
                             'Tirat Carmel': ['Nahariyya', 'Afula', 'Haifa', 'Netanya'],
                             'Umm al-Fahm': ['Kefar Sava', 'Raanana', 'Afula', 'Haifa', 'Netanya', 'Pardesiya',
                                             'Hod Hasharon'],
                             'Yavne': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana', 'Ramat Gan',
                                       'Ashdod',
                                       'Bnei Brak', 'Tel-Aviv', 'Hod Hasharon'],
                             'Yehud-Monosson': ['Jerusalem', 'Kefar Sava', 'Petah Tikva', 'Holon', 'Raanana',
                                                'Ramat Gan',
                                                'Ashdod', 'Bnei Brak', 'Netanya', 'Tel-Aviv', 'Pardesiya',
                                                'Hod Hasharon'],
                             'Yokneam': ['Nahariyya', 'Afula', 'Haifa', 'Netanya', 'Pardesiya']}

cities_less_50_km_heb = {'עפולה': ['נהריה', 'עפולה', 'צפת', 'חיפה', 'פרדסיה'],
                         'אריאל': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'בני ברק', 'נתניה',
                                   'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'אשדוד': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                   'תל אביב-יפו', 'הוד השרון'], 'אשקלון': ['חולון', 'אשדוד'],
                         'עראבה': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         "באקה-ג'ת": ['כפר סבא', 'פתח תקווה', 'רעננה', 'עפולה', 'חיפה', 'רמת גן', 'בני ברק', 'נתניה',
                                      'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'בת ים': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק', 'נתניה',
                                   'תל אביב-יפו', 'פרדסיה', 'הוד השרון'], 'באר שבע': ['באר שבע'], 'בית שאן': ['עפולה'],
                         'בית שמש': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רמת גן', 'אשדוד', 'בני ברק',
                                     'תל אביב-יפו', 'הוד השרון'],
                         'באקה אל-גרבייה': ['כפר סבא', 'פתח תקווה', 'רעננה', 'עפולה', 'חיפה', 'רמת גן', 'בני ברק',
                                            'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'ביתר עילית': ['ירושלים', 'פתח תקווה', 'חולון', 'רמת גן', 'אשדוד'],
                         'בני ברק': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                     'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'], 'דימונה': ['באר שבע'],
                         'אלעד': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                  'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'גבעתיים': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                     'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'גבעת שמואל': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד',
                                        'בני ברק', 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'חדרה': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'עפולה', 'חיפה', 'רמת גן', 'בני ברק',
                                  'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'], 'חיפה': ['נהריה', 'עפולה', 'חיפה'],
                         'הרצליה': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק', 'נתניה',
                                    'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'כפר סבא': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק', 'נתניה',
                                     'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'חולון': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                   'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'ירושלים': ['ירושלים', 'פתח תקווה', 'חולון', 'רמת גן', 'בני ברק'],
                         'כרמיאל': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'כפר קאסם': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                      'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'קריית אתא': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'קריית ביאליק': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'קריית גת': ['ירושלים', 'חולון', 'אשדוד', 'באר שבע'],
                         'קריית מלאכי': ['ירושלים', 'פתח תקווה', 'חולון', 'רמת גן', 'אשדוד', 'בני ברק', 'תל אביב-יפו',
                                         'הוד השרון'], 'קריית מוצקין': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'קריית אונו': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד',
                                        'בני ברק', 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'קריית שמונה': ['צפת'], 'קריית ים': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'לוד': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'], 'מעלה אדומים': ['ירושלים'],
                         'מעלות תרשיחא': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'מגדל העמק': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'מודיעין עילית': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד',
                                           'בני ברק', 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'מודיעין- מכבים- רעות': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן',
                                                  'אשדוד', 'בני ברק', 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         "מע'אר": ['נהריה', 'עפולה', 'צפת', 'חיפה'], 'נצרת': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'נצרת עלית': ['נהריה', 'עפולה', 'צפת', 'חיפה'], 'נשר': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'נס ציונה': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                      'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'נתניה': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'בני ברק', 'נתניה',
                                   'תל אביב-יפו', 'פרדסיה', 'הוד השרון'], 'נתיבות': ['אשדוד', 'באר שבע'],
                         'אופקים': ['באר שבע'],
                         'אור עקיבא': ['כפר סבא', 'פתח תקווה', 'רעננה', 'עפולה', 'חיפה', 'בני ברק', 'נתניה',
                                       'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'אור יהודה': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד',
                                       'בני ברק', 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'נוף הגליל': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'פתח תקווה': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד',
                                       'בני ברק', 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'קלנסווה': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'עפולה', 'רמת גן', 'בני ברק', 'נתניה',
                                     'תל אביב-יפו', 'פרדסיה', 'הוד השרון'], 'רהט': ['אשדוד', 'באר שבע'],
                         'רמת גן': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                    'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'רמת השרון': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק', 'נתניה',
                                       'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'רמלה': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                  'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'רחובות': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                    'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'ראשון לציון': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד',
                                         'בני ברק', 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'ראש העין': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                      'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'סכנין': ['נהריה', 'עפולה', 'צפת', 'חיפה'], 'שדרות': ['אשדוד', 'באר שבע'],
                         'שפרעם': ['נהריה', 'עפולה', 'צפת', 'חיפה'], 'טמרה': ['נהריה', 'עפולה', 'צפת', 'חיפה'],
                         'טייבה': ['כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'עפולה', 'רמת גן', 'בני ברק', 'נתניה',
                                   'תל אביב-יפו', 'פרדסיה', 'הוד השרון'], 'טבריה': ['נהריה', 'עפולה', 'צפת'],
                         'טירת כרמל': ['נהריה', 'עפולה', 'חיפה', 'נתניה'],
                         'אום אל-פחם': ['כפר סבא', 'רעננה', 'עפולה', 'חיפה', 'נתניה', 'פרדסיה', 'הוד השרון'],
                         'יבנה': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד', 'בני ברק',
                                  'תל אביב-יפו', 'הוד השרון'],
                         'יהוד-מונסון': ['ירושלים', 'כפר סבא', 'פתח תקווה', 'חולון', 'רעננה', 'רמת גן', 'אשדוד',
                                         'בני ברק', 'נתניה', 'תל אביב-יפו', 'פרדסיה', 'הוד השרון'],
                         'יקנעם עילית': ['נהריה', 'עפולה', 'חיפה', 'נתניה', 'פרדסיה']}



# for k, v in cities_less_50_km_english.items():
#     city_english_key = k  # str
#     list_of_cities_english = v  # list
#
#     city_hebrew_key = cities_in_israel_en_heb.get(city_english_key)
#
#     list_of_cities_heb = []
#     for city in list_of_cities_english:
#         temp_city = cities_in_israel_en_heb.get(city)
#         list_of_cities_heb.append(temp_city)
#
#     cities_less_50_km_heb[city_hebrew_key] = list_of_cities_heb
#
# print(cities_less_50_km_heb)

